apiVersion: v1
kind: Service
metadata:
  name: my-k8s-api-service
  labels:
    app: my-k8s-api-service
spec:
  selector:
    app: my-k8s-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
